### ISSUE TITLE
flake8 was not found in this python distribution.

### ISSUE THREAD

**Issue by natephysics** [mlshapiro/jupyterlab-flake8#12]
Hi shapiro, 

Great plugin you got here. I've been waiting for your update for a while and I'm excited I'm finally getting a chance to use it. I'm running a jupyerhub server with the default environment as jupyterlab. I'm getting a strange error. I have flake8 installed, I can run it from the command line with any user including root. When I load up a notebook it periodically, I get an error in browser saying: "flake8 was not found in this python distribution," along with some instructions on how to install it. But after accepting the error, the plugin lints the code and returns the correct errors. I'm getting the error window each time before the linting of the code is refreshed. 

I'm also not sure if the plugin is supposed to work this way, but instead of just linting the cell I've just returned, it seems to be linting all the cells anytime I return any of the cells. Again, this might be working as intended, but I thought I would bring it up just in case.

**Comment by mlshapiro** [comment]
This is likely due to using conda environments. The extension now supports conda environments as of 0.3.0. 

Try again and make sure to set the `conda_env` setting for this extension and it will use a specific environment to look for the `flake8` dependency.

Feel free to re-open this issue if this does not fix your situation.

**Comment by andreas-h** [comment]
I have the same problem, with v0.3.1, behind a JupyterHub proxy:

I want to use my conda environment called *jupyter_2019* which does have `flake8` installed:

    (jupyter_2019) $ conda env list
    # conda environments:
    #
    base                     /home/conda
    jupyter_2019          *  /home/conda/envs/jupyter_2019
    lamos_2019.1             /home/conda/envs/lamos_2019.1
    lamos_2019.2b            /home/conda/envs/lamos_2019.2b
                             /opt/software/conda
                             /opt/software/conda/envs/lamos_2019.1
    
    (jupyter_2019) $ which flake8
    /home/conda/envs/jupyter_2019/bin/flake8

In the extension settings, I have this:

    // [missing schema title]
    // Conda environment to use for flake8 linter
    "conda_env": "jupyter_2019",

Still, I get the *Flake8 was not found in this python environment* error.

What else can I do to debug this?
