### ISSUE TITLE
Config not found

### ISSUE THREAD

**Issue by ivigamberdiev** [mlshapiro/jupyterlab-flake8#13]
I create config in the same directory as the notebook, which I want to lint, but have 'Settings not found (jupyterlab-flake8)' in jupyter lab log. What am I doing wrong?

**Comment by mlshapiro** [comment]
Hm... not exactly sure. I just updated the extension for Jupyter Lab 1.x and refactored the settings integration. Do you mind to try again and re-open the issue if its still a problem?
