### ISSUE TITLE
Disable for non-python cells, i.e. when using ipython magics

### ISSUE THREAD

**Issue by sntgluca** [mlshapiro/jupyterlab-flake8#15]
Hi!

great idea! Thank you for implementing this.

I think it should only work on python cells :)
In notebooks with magic scripts, i.e. bash, cells are cluttered with incorrect error messages:

<img width="633" alt="screen shot 2019-02-06 at 10 18 45" src="https://user-images.githubusercontent.com/10941257/52331575-d4c7c180-29f8-11e9-8324-b64cc1bc4cde.png">

I suggest to disable it when cell magics are found.
Thanks!

**Comment by thejens** [comment]
+1
