### ISSUE TITLE
How to remove the extention?

### ISSUE THREAD

**Issue by FrankKirin** [mlshapiro/jupyterlab-flake8#17]

**Comment by dbrakman** [comment]
The [documentation](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#installing-extensions) for jupyterlab suggests
```jupyter labextension uninstall jupyterlab-flake8```

Does the above error out or result in an incomplete uninstall?

**Comment by FrankKirin** [comment]
It works, thank you very much. I am sorry that I just read the documentation about jupyterlab-flake8 extention. But it will be clear if we add the uninstall guide to the README file :).
