### ISSUE TITLE
Change linter for IPython2 notebooks

### ISSUE THREAD

**Issue by dbrakman** [mlshapiro/jupyterlab-flake8#18]
Is it possible to select a flake8 linter for ipython 2 kernels?

We're in the process of removing dependencies that block the upgrade to python3 and would like to see where we have unused imports. But since the flake8 module for python3 treats python2 print statements, etc. as syntax errors, pyflakes can't parse the file to tell us what we'd like to know.

I imagine the recommended workaround is writing 2-3 compatible code, but I'm looking to see what tools can be used before we dictate style changes across the organization.

**Comment by mlshapiro** [comment]
you should now be able to set a conda environment using the *Advanced Settings* in v0.3.0 If your conda environment in Python 2.x, it should still work the same. 

Feel free to re-open if this is not possible.
