### ISSUE TITLE
Wrongly reporting W391 blank line at end of file

### ISSUE THREAD

**Issue by memeplex** [mlshapiro/jupyterlab-flake8#20]
My file ends with a newline, as usual. Calling flake8 from the terminal on that file reports nothing wrong. Yet jupyterlab flake8 extension insists in reporting W391. If I now add another new line at the end of the file, flake8 correctly reports W391 in both cases (terminal and jupyterlab). I'm not sure how you're calling flake8 but it seems to me like some additional newline is being inadvertently added to its input.

**Comment by mlshapiro** [comment]
Probably due to https://github.com/mlshapiro/jupyterlab-flake8/blob/master/src/index.ts#L375

Need to provide check that the text is not just `\n`

**Comment by mlshapiro** [comment]
actually - may be somewhere else, will take a look later.

**Comment by mlshapiro** [comment]
should be fixed in 0.3.2

**Comment by memeplex** [comment]
Thanks!
