### ISSUE TITLE
cannot work in windows 10?

### ISSUE THREAD

**Issue by andibuwono** [mlshapiro/jupyterlab-flake8#21]
Hi, i'm currently have difficulty to get the extension work at my system (Windows 10 1903).

       jupyter==1.0.0
       jupyter-client==5.3.1
       jupyter-console==6.0.0
       jupyter-core==4.5.0
       jupyterlab==1.1.2
       jupyterlab-server==1.0.6

        @ijmbarr/jupyterlab_spellchecker v0.1.5 enabled  ok
        @jupyter-widgets/jupyterlab-manager v1.0.2 enabled  ok
        @jupyterlab/commenting-extension v0.2.0 enabled  ok
        @jupyterlab/geojson-extension v1.0.0 enabled  ok
        @jupyterlab/shortcutui v0.4.0 enabled  ok
        @lckr/jupyterlab_variableinspector v0.3.0 enabled  ok
        @mflevine/jupyterlab_html v0.1.4 enabled  ok
        @pyviz/jupyterlab_pyviz v0.8.0 enabled  ok
        ipyevents v1.6.3 enabled  ok
        jupyter-gmaps v0.9.0 enabled  ok
        jupyter-leaflet v0.11.1 enabled  ok
        jupyter-threejs v2.1.1 enabled  ok
        jupyterlab-cpustatus v1.0.0 enabled  ok
        jupyterlab-dash v0.1.0-alpha.3 enabled  ok
        jupyterlab-datawidgets v6.2.0 enabled  ok
        jupyterlab-flake8 v0.3.1 enabled  ok
        jupyterlab-jupytext v1.0.2 enabled  ok
        jupyterlab-python-bytecode v0.7.0 enabled  ok
        jupyterlab-python-file v0.3.0 enabled  ok
        jupyterlab-spreadsheet v0.2.0 enabled  ok
        jupyterlab_bokeh v1.0.0 enabled  ok

when i see in the terminal, it pass up side down multiline command  as below.

![2019-09-12_220044](https://user-images.githubusercontent.com/9608246/64796120-6ad45380-d5a9-11e9-8057-107df4ca676f.png)

Thanks before

**Comment by mlshapiro** [comment]
the reason the command looks backwards is the plugin is piping the contents of your file/notebook into the linter

try 0.3.2 - i can't test on powershell so I apologize if this does not work.
