### ISSUE TITLE
Support more modern conda distribution

### ISSUE THREAD

**Issue by andreas-h** [mlshapiro/jupyterlab-flake8#24]
It seems to me that the extension does not properly work with modern conda installations.

As I laid out in https://github.com/mlshapiro/jupyterlab-flake8/issues/12#issuecomment-532275281 it doesn't work for me.  So I dug into the source code and found that in order to activate the conda environment, the code calls `activate CONDA_ENV`.  However, on my current conda installation, the `activate` script is not in the default `$PATH` which one gets by souring `conda/etc/profile.d/conda.sh`.

It would work properly when the extension would call `conda activate CONDA_ENV` instead.

As a workaround, I created a script called `activate` in the `condabin` folder (which is the only addition to the `$PATH` in recent conda installations) which looks like this:

    #!/bin/sh
    . /path/to/anaconda/etc/profile.d/conda.sh
    conda activate $!

Should I prepare a PR adding the `conda` to the relevant call, or do you want to keep backward compatibility to deprecated conda installations?  In that case, maybe a new configuration parameter would be a good idea.

What do you think?

**Comment by mlshapiro** [comment]
Definitely - I will fix this when I have time to merge in #22
