### ISSUE TITLE
jupyterlab-flake8 always lost connection with terminal

### ISSUE THREAD

**Issue by kylechan2017** [mlshapiro/jupyterlab-flake8#28]
recently i always run into this error:
`jupyterlab-flake8 ran into an issue connecting with the terminal. Please try reloading the browser or re-installing the jupyterlab-flake8 extension.`
I tried re-install but the same problem occurred

**Comment by mlshapiro** [comment]
@kylechan2017 I'm not sure exactly how to help you - do you have any more information you can share about what platform you are running and when this happens? Do the browser console logs say anything in particular?

**Comment by kylechan2017** [comment]
@mlshapiro Sorry for late reply. Here is the error from browser console:
`widget.js:798 Uncaught (in promise) TypeError: Cannot read property 'future' of null
    at Function.execute (widget.js:798)`

**Comment by dberzano** [comment]
Same problem here with `jupyterlab-flake8 v0.4.1`.

**Comment by gschaffner** [comment]
I also get this error with v0.4.1.

**Comment by luna983** [comment]
Had the same error

**Comment by ejolly** [comment]
Same issue, running on mac OS 10.15.3 (Catalina), Chrome Version 80.0.3987.87. Here's the output of my `conda list | grep jup`:  
```
jupyter                   1.0.0                    py37_7
jupyter-contrib-core      0.3.3                    pypi_0    pypi
jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
jupyter-latex-envs        1.4.6                    pypi_0    pypi
jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
jupyter_client            5.3.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.6.1                    py37_0
jupyterlab                1.2.5              pyhf63ae98_0
jupyterlab-code-formatter 1.0.3                    pypi_0    pypi
jupyterlab_server         1.0.6                      py_0
jupytext                  1.3.3                    pypi_0    pypi
```

**Comment by spdavern** [comment]
I also get the pop-up window error reported by kylechan2017.   I'm running mac OS 10.15.3 (Catalina), Chrome 80.0.3987.116 (Official Build) (64-bit). Here's the output of my `conda list | grep jup`:
`jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.1.0                      py_0  
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.6.1                    py37_0  
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
jupyterlab                1.2.5              pyhf63ae98_0  
jupyterlab-git            0.9.0                    pypi_0    pypi
jupyterlab_server         1.0.6                      py_0  `

**Comment by mlshapiro** [comment]
this may be happening due to the change on mac from bash to zsh. It seems like the linter plugin can't figure out if it is on posix or nt. I'm seeing in the browser logs:

```
python -c "import os; print(os.name)"

# looking for `posix` or `nt` here
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
```

I'll flush the terminal first before asking for the OS

**Comment by mlshapiro** [comment]
To be clear, I have not been able to recreate the exact error your are seeing here

**Comment by mlshapiro** [comment]
@kylechan2017 @ejolly @spdavern @luna983 please give v0.5.0 a try and let me know if you still experience this issue. 

Bit of a shot in the dark, but it may work.

**Comment by ejolly** [comment]
0.5.0 is working for me without any issues (so far)!

**Comment by ejolly** [comment]
Ok actually I am noticing one issue, but it's really not a usage problem. Within jupyterlab, the extension always creates a terminal that linting messages get logged to (when the option is turned on). But if that terminal is ever closed, I need to refresh the browser to get the extension working again.

For example:
1) Create a new notebook (extension creates a terminal and linting works fine)
2) Shutdown and/or delete notebook
3) Create a new notebook or reopen previous (linting works fine)
4) Shutdown and/or delete notebook *and* close terminal within juptyerlab (error message appears for any new or old notebooks and requires browser refresh)

**Comment by spdavern** [comment]
I installed jupyterlab-flake8 v0.5.0.  Opening certain jupyter notebooks causes the error message and jupyter to become unresponsive.

For example:
1. clone [this Github repo](https://github.com/spdavern/breaks_flake8) or download [this file](https://github.com/spdavern/breaks_flake8/blob/master/Hypothesis_test_review_and_power.ipynb)
2. Start jupyter lab (extension creates a terminal)
3. Create new notebook (linting works fine)
4. Open 'Hypothsis_test_review_and_power.ipynb' (error message appears - no kernel started for new notebook, jupyter lab unresponsive)

**Comment by ejolly** [comment]
I've had more of a chance to work with the extension today and can reproduce the error @spdavern mentioned. Even with a new notebook, after a few minutes and > 10 cells jupyterlab completely hangs, then the kernel fails to connect to the notebook, and ultimately the server itself becomes unresponsive (`ctrl+c`/`ctrl+d` don't work) and I have to use `kill` to end all jupyter processes.

**Comment by mlshapiro** [comment]
> I installed jupyterlab-flake8 v0.5.0. Opening certain jupyter notebooks causes the error message and jupyter to become unresponsive.
> 
> For example:
> 
>     1. clone [this Github repo](https://github.com/spdavern/breaks_flake8) or download [this file](https://github.com/spdavern/breaks_flake8/blob/master/Hypothesis_test_review_and_power.ipynb)
> 
>     2. Start jupyter lab (extension creates a terminal)
> 
>     3. Create new notebook (linting works fine)
> 
>     4. Open 'Hypothsis_test_review_and_power.ipynb' (error message appears - no kernel started for new notebook, jupyter lab unresponsive)

Thank you for this example, when I have a second in the next week I'll take a look!

**Comment by bluss** [comment]
I've seen this problem with jupyter-lab 3.1.18 and couldn't find any error message (nothing in jupyter lab's output)
