### ISSUE TITLE
PEP8 is flagging Jupyterlab magics

### ISSUE THREAD

**Issue by notuntoward** [mlshapiro/jupyterlab-flake8#29]
This is very useful.  Thanks.

One small problem with it is that it flags Jupyterlab magics as syntax errors.  For example, if a cell has a line like this:

`%load_ext autoreload`

it's flagged as an error.

**Comment by memeplex** [comment]
It seems to be just the first magic in the notebook that is flagged as an error, for example:

![image](https://user-images.githubusercontent.com/2845433/72688391-80bccc80-3ae5-11ea-978d-96cc35018f0a.png)

Also, marking that line as `noqa` removes the spurious error.

**Comment by memeplex** [comment]
Recently a PR was merged to fix this issue, but it's only ignoring cell magics (`%%`), not inline magics (`%`).

**Comment by mlshapiro** [comment]
@notuntoward this should be fairly easy to fix when I can find a moment. I'd welcome a PR - See #15 and resolution f1f83694acf927a999927240874ea8dd3d6627d7

**Comment by notuntoward** [comment]
Thanks!
