### ISSUE TITLE
.flake8 config file will be ignored

### ISSUE THREAD

**Issue by sutiv** [mlshapiro/jupyterlab-flake8#30]
If I place a .flake8 or setup.cfg (like its written in the [flake8-docu](http://flake8.pycqa.org/en/latest/user/configuration.html#project-configuration)) in the current directory, it will be ignored.

If I manipulate the file `~/.jupyter/lab/user-settings/jupyterlab-flake8/plugins.jupyterlab-settings` and add `"configuration_file": "~/PATH_TO_MY_REPO/setup.cfg"` everything works well.

Our problem with this work-around is, that we are working on AWS SageMaker and have to deploy a ready-to-use environment and we do not want to edit the user-settings just to use a formatter.

**Comment by mlshapiro** [comment]
I'm not able to recreate this issue. If the `configuration_file` is not defined, the plugin will call `<notebook text> | flake8 --exit-zero`.

If you open a terminal on sage maker and run `test | flake8 --exit-zero` does the output reflect your setup in setup.cfg?

**Comment by sutiv** [comment]
okay, your command works, but only if I got a `.flake8` or `setup.cfg` in each folder of my repository.
I thought a `setup.cfg` in the root directory of my repository is enough.

Are there any plans to implement this feature? My wish would be to put a single setup.cfg in the root of a repository and all files in that repo are affected?

Unfortunately we are currently unable to use your extension because an error message is displayed when opening a `.py` file that is too large (or contains to much unformatted code) and the Jupyterlab crashes.
