### ISSUE TITLE
Extension Slows Large Notebooks to A Crawl

### ISSUE THREAD

**Issue by pmarcellino** [mlshapiro/jupyterlab-flake8#38]
I have the extension installed, and it is working very well, except whenever I attempt to use it on a large notebook, the whole notebook slows dramatically. Each cell time is technically unaffected, but the UI slows dramatically for a few seconds after each cell run.

**Comment by mlshapiro** [comment]
Unfortunately the implementation I used here isn't super compatible with large notebooks.  It takes the entire notebook as a string and passes it to `flake8` in a terminal, then parses the result.

It currently lints every time you move a cell or save - we could add a "lint" command and an option to turn off linting on save?

**Comment by mlshapiro** [comment]
The latest version of the extension (0.7.1) has a setting `lint_on_change` - set this to false (or toggle the "View" -> "Run Lint on change") and the linter will not run everytime you change a cell.

To lint the view, pull up the command pallette and select "Lint active notebook" or "Lint active editor"
