### ISSUE TITLE
build error: @types/codemirror has no default export

### ISSUE THREAD

**Issue by mprogram** [mlshapiro/jupyterlab-flake8#5]
Shouldn't the source (`src`) and `tsconfig.json` be included with the release, and even if so it fails for me to build it from the source on `import CodeMirror from 'codemirror'`as the latter has no default export. I'm using JupyterLab 0.33.4 and `npm = 6.2.0`

**Comment by mlshapiro** [comment]
i am following the lead of the primary jupyterlab extensions using the `import CodeMirror from 'codemirror'` (see https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror-extension/src/index.ts#L4).  I also see this error upon building in a development environment, but it does not stop me from failing to build. 

Please post the steps you used to build from source and i'll try to recreate if i have time.

**Comment by mprogram** [comment]
Surely, the steps are straightforward (assuming any top-level and empty directory like or instead of `~`):

`cd ~`
`git clone git://github.com/mlshapiro/jupyterlab-flake8.git`
`#Cloning into 'jupyterlab-flake8'...`
`#remote: Counting objects: 176, done.`
`#remote: Compressing objects: 100% (19/19), done.`
`#remote: Total 176 (delta 13), reused 31 (delta 11), pack-reused 141`
`#Receiving objects: 100% (176/176), 258.71 KiB | 649.00 KiB/s, done.`
`#Resolving deltas: 100% (77/77), done.`

`cd jupyterlab-flake8`
`npm install`
`#added 103 packages from 897 contributors and audited 14850 packages in 3.61s`
`#found 0 vulnerabilities`

`npm run build`
`#> jupyterlab-flake8@0.2.1 build ~/jupyterlab-flake8`
`#> tsc`

`#node_modules/@jupyterlab/codemirror/lib/editor.d.ts:1:8 - error TS1192: Module '"~/jupyterlab-flake8/node_modules/@types/codemirror/index"' has no default export.`

`#1 import CodeMirror from 'codemirror';`
`#_________~~~~~~~~~~`


`#npm ERR! code ELIFECYCLE`
`#npm ERR! errno 1`
`#npm ERR! jupyterlab-flake8@0.2.1 build: 'tsc'`
`#npm ERR! Exit status 1`
`#npm ERR! `
`#npm ERR! Failed at the jupyterlab-flake8@0.2.1 build script.`
`#npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`#npm ERR! A complete log of this run can be found in:`
`#npm ERR!     ~/.npm/_logs/2018-08-01T19_50_53_529Z-debug.log`


The situation is even more dramatic from the released source (shown with partial output is only the last step):

`wget https://registry.npmjs.org/jupyterlab-flake8/-/jupyterlab-flake8-0.2.1.tgz # curl -O`
`tar -xf jupyterlab-flake8-0.2.1.tgz`
`cd package`
`npm run build`
`#> jupyterlab-flake8@0.2.1 build ~/package`
`#> tsc`

`#Version 2.9.2`
`#Syntax:   tsc [options] [file ...]`

`#Examples: tsc hello.ts`
`#__________tsc --outFile file.js file.ts`
`#__________tsc @args.txt`

`#Options:`
`# -h, --help                                         Print this message.`
`# --all                                              Show all compiler options.`
`# -v, --version                                      Print the compiler's version.`
`#…`

**Comment by mlshapiro** [comment]
ah i forgot to include `allowSyntheticImports` into tsconfig.json. This will fix `npm run build`. Fixed in 043b6610772db41abb0821c12b2b11267ccccf34, released 0.2.2

The version published to npm is not the source, so you can't do what you are trying to do in your second example. You can install the extension from npm using jupyter with:

```
jupyter labextension install jupyterlab-flake8
```
