### ISSUE TITLE
Flake8 not installed warning blocks interface

### ISSUE THREAD

**Issue by jbusecke** [mlshapiro/jupyterlab-flake8#6]
I was able to install the extension and it worked yesterday, but I randomly get a message that `flake8` is not installed:

<img width="689" alt="screen shot 2018-08-05 at 12 18 21 pm" src="https://user-images.githubusercontent.com/14314623/43687812-399d7fea-98aa-11e8-8c59-a876a6521684.png">

This blocks all my work and its also not true. I installed flake 8 with conda, and for a short period it worked. Then I disabled it in the `View` Menu, and tried to reactivate it today. 

Sorry for the scattered error description, but I havent been able to figure out in more detail what is going on.

**Comment by mlshapiro** [comment]
Hello - sorry to see your having trouble. 
I throw this error when the terminal returns a traceback from python that includes the message `'command not found'`, so for some reason your jupyter terminal is having trouble finding `flake8`.  

A few things to try:

- open the terminal program and try to run `flake8`, for instance run:

```
$ flake8 --help
```

- are you using conda environments? I have noticed that some issues crop up when using conda environments. Sometimes `flake8` will be available on the command line from a different environment than the one you launched jupyter in, which can cause problems.
- If none of this provides any clues, turn on the option for **Output Flake8 Browser Console Logs ** and try to run the linter in a notebook. Copy the browser console (accessible in Chrome, press F12, in Firefox Tools ->Web Developer ->Web Console) to this issue and we may be able to figure out whats going on.

**Comment by mlshapiro** [comment]
This may be solved by updates in 0.3.0.  Let me know if this is still an issue after the update.
