### ISSUE TITLE
Enable/disable the linter from the text editor settings

### ISSUE THREAD

**Issue by santiagobasulto** [mlshapiro/jupyterlab-flake8#9]
Hello! Is there any way to change JupyterLab settings and enable/disable flake8 check? Or only from the command palette? Thanks!

![image](https://user-images.githubusercontent.com/872296/45786347-71561680-bc46-11e8-9172-2dccc6bbd1a6.png)

**Comment by santiagobasulto** [comment]
👍 great, I'd love to help but I'm not really familiar to the jupyterlab API, I'll keep an eye on your change to get more familiarized.

**Comment by mlshapiro** [comment]
started working on this on feature/settings

**Comment by santiagobasulto** [comment]
@mlshapiro Hey Marc! I was playing around with the extension but I'm still a little bit unsure about the architecture of juptyerlab extensions. How can you read, from the extension, some overall configuration?

**Comment by mlshapiro** [comment]
@santiagobasulto this is implemented in 0.3.0

Thanks!
